{{ if .Values.btc.bitcoind.storage.size }}
{{ if or .Values.btc.enabled .Values.keepUnusedEssentialPVCs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.btc.bitcoind.storage.size }}
{{ end }}
{{ end }}