{{ if .Values.doge.dogecoind.storage.size }}

{{ if or .Values.doge.enabled .Values.keepUnusedEssentialPVCs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dogecoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.doge.dogecoind.storage.size }}
{{ end }}

{{ end }}