{{ if .Values.ltc.litecoind.storage.size }}
{{ if or .Values.ltc.enabled .Values.keepUnusedEssentialPVCs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoind-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ltc.litecoind.storage.size }}
{{ end }}
{{ end }}