{{ if .Values.tron_fullnode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tron-output-directory
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tron_fullnode.storage.size }}
{{ end }}