#
# General
#

namespace: shkeeper
external_ip: 0.0.0.0

dev:
  imagePullSecrets:

storageClassName:

keepUnusedEssentialPVCs: true

#
# Shkeeper
#

shkeeper:
  image: vsyshost/shkeeper:2.3.1
  port: 5000
  storage:
    size: 10Gi

mariadb:
  storage:
    size: 10Gi

#
# BTC and forks
#

btc:
  enabled: true
  mainnet: true
  bitcoind:
    image: vsyshost/bitcoind:27.0
    storage:
      size: 15Gi

ltc:
  enabled: true
  mainnet: true
  litecoind:
    storage:
      size: 15Gi

doge:
  enabled: true
  mainnet: true
  dogecoind:
    storage:
      size: 15Gi
#
# Tron
#

tron_fullnode:
  image: vsyshost/javatron:GreatVoyage-v4.7.7
  enabled: false
  url: http://java-tron:8090
  solidity_url: http://java-tron:8091
  mainnet: true
  JAVA_TOOL_OPTIONS: ""
  nodeSelector: {}
  tolerations: []
  storage:
    size: 2000Gi

tron_shkeeper:
  image: vsyshost/tron-shkeeper:1.1.7
  host: 'tron-shkeeper'
  port: 6000
  storage:
    size: 1Gi
  redis:
    storage:
      size: 1Gi

trx:
  enabled: false
usdt:
  enabled: false
usdc:
  enabled: false

#
# Ethereum
#

eth_fullnode:
  enabled: false
  url: http://ethereum:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []
  storage:
    size: 1000Gi

ethereum_shkeeper:
  image: vsyshost/ethereum-shkeeper:1.1.8

eth:
  enabled: false
eth_usdt:
  enabled: false
eth_usdc:
  enabled: false
eth_pyusd:
  enabled: false

#
# Monero
#

monero:

  enabled: false
  image: vsyshost/monero:v0.18.1.2
  mainnet: true

  fullnode:
    enabled: false
    monerod:
      host: "monerod"
      port: "1111"
      user: "monerod"
      password: "monerod"
      nodeSelector: {}
      tolerations: []
      storage:
        size: 20Gi

  monero_wallet_rpc:
    storage:
      size: 10Gi

#
# BNB
#

bnb_fullnode:
  enabled: false
  url: http://bnb:8545
  mainnet: true
  nodeSelector: {}
  tolerations: []
  storage:
    size: 3100Gi

bnb_shkeeper:
  image: vsyshost/bnb-shkeeper:1.1.5

bnb:
  enabled: false
bnb_usdt:
  enabled: false
bnb_usdc:
  enabled: false

#
# XRP
#

xrp_fullnode:
  enabled: false
  url: http://xrp:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []

xrp_shkeeper:
  image: vsyshost/xrp-shkeeper:1.0.12

xrp:
  enabled: false

#
# Polygon
#

polygon_fullnode:
  enabled: false
  url: http://polygon:51234
  mainnet: true
  nodeSelector: {}
  tolerations: []
  heimdall:
    storage:
      size: 1000Gi
  bor:
    storage:
      size: 1000Gi

polygon_shkeeper:
  image: vsyshost/polygon-shkeeper:1.0.3

matic:
  enabled: false
polygon_usdt:
  enabled: false
polygon_usdc:
  enabled: false

#
# Avalanche
#

avalanche_fullnode:
  enabled: false
  url: http://avalanche:9650/ext/bc/C/rpc
  mainnet: true
  nodeSelector: {}
  tolerations: []
  storage:
    size: 1000Gi

avalanche_shkeeper:
  image: vsyshost/avalanche-shkeeper:1.0.0

avax:
  enabled: false
avalanche_usdt:
  enabled: false
avalanche_usdc:
  enabled: false

#
# BTC Lightning
#

btc_lightning:
  enabled: false
  network: mainnet

  lnd:
    image: vsyshost/lndinit:v0.1.22-beta-lnd-v0.18.3-beta
    rest_url: https://lightning-lnd-rest:8080
    p2p_port: 9735
    storage:
      size: 10Gi

  rtl:
    image: shahanafarooqui/rtl:v0.15.4
    web_url: http://rtl:3000
    logout_redirect_link: http://shkeeper:5000/wallet/BTC-LIGHTNING
    storage:
      size: 10Gi
#
# Solana
#

solana_fullnode:
  enabled: false
  url: http://here-should-be-url-to-your-solana-rpc-node/
  mainnet: true
  nodeSelector: {}
  tolerations: []

solana_shkeeper:
  image: vsyshost/solana-shkeeper:1.0.2

sol:
  enabled: false
solana_usdt:
  enabled: false
solana_usdc:
  enabled: false
solana_pyusd:
  enabled: false