{{ if .Values.monero.monero_wallet_rpc.storage.size }}
{{ if or .Values.monero.enabled .Values.keepUnusedEssentialPVCs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monero-wallet-rpc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monero.monero_wallet_rpc.storage.size }}
{{ end }}
{{ end }}
